version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: jongoun-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - jongoun

    db:
        image: mysql:8.0
        container_name: jongoun-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - jongoun

    nginx:
        image: nginx:alpine
        container_name: jongoun-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - jongoun

networks:
    jongoun:
        driver: bridge

volumes:
    dbdata:
        driver: local
