version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: jongoun-app
        container_name: jongoun-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - jongoun
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: jongoun-web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - jongoun
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: jongoun-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3309:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - jongoun

networks:
    jongoun:

volumes:
    dbdata:
